[programs.localnet]
messengerapp = "6Xb1pyn8vLkbVSzivWcTpnKEUz3TNfJYZuXsjyTkkLg6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/metalgear/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"
